### ISSUE TITLE
dryRun option

### ISSUE THREAD

**Issue by Toilal** [stevelacy/bump-regex#1]
Would you consider implementing a `dryRun` option to retrieve the existing version from the callback ?

**Comment by stevelacy** [comment]
PR?

**Comment by stevelacy** [comment]
Actually - the existing version is returned already:
https://github.com/stevelacy/bump-regex/blob/master/index.js#L27

**Comment by Toilal** [comment]
Sorry, I was wrong about the source of this issue, I think this module is perfectly fine and the dryRun option should be implemented in the `gulp-bump` plugin.
