### ISSUE TITLE
'_version' is unintentionally bumped

### ISSUE THREAD

**Issue by cschuff** [stevelacy/bump-regex#14]
In a JSON like this bump-regex will bump '_version' instead of 'version':
```
{
  _version: '2.0.0',
  app: {
    type: 'application',
    applicationVersion: {
      version: '1.0.0'
    }
  }
}
```

This is due to the regex you are using:
![31-03-_2017_13-29-44](https://cloud.githubusercontent.com/assets/194434/24548577/2a0234da-1616-11e7-8951-35c3c98e79d7.png)

I was able to fix this (at least for my simple scenario) by doing this:
`bump({ key: '[^_]version' })`

It would actually be all fine if you omit the '?' from 
`'([<|\'|\"]?' + opts.key + '...`

I'm not sure about the implications. So let me know if this is a valid fix and I'll be happy to submit a pull request along with some additional tests.

BR
Chris

**Comment by stevelacy** [comment]
The `?` identifier will match any prefix, such as `^`, `~`, etc. and is required for normal semver usage. It could be changed to a grouping set of certain prefix characters, but I do not know every prefix used by versioning types.

**Comment by cschuff** [comment]
Can you elaborate a little more on 'normal semver usage'. In my node projects I usually store the version in package.json and evtl. additional .txt, .xml, .json or .js files. None of those would require a prefix to the string 'version'. 

You will surely need the prefixes in the version string like ^1.0.0 but I am talking about the actual string 'version' that you use as a default key. Can't see why a prefix is needed there. And if someone needs a prefix one can still easily change the key option to sth. like '_version'.

BR
Chris
