### ISSUE TITLE
support for premajor, preminor, prepatch

### ISSUE THREAD

**Issue by zam6ak** [stevelacy/bump-regex#25]
Is there a way to bump using `premajor`, `preminor` or `prepatch`?
For example, I would like to go from v1.5.0 to 1.6.0-rc.0

with `prerelease` (existing)you cannot do this....
```
> semver --preid rc --increment prepatch 1.5.0
1.5.1-rc.0
```

but with `preminor` you can
```
> semver --preid rc --increment preminor 1.5.0
1.6.0-rc.0
```

**Comment by stevelacy** [comment]
I'll accept a PR assuming that https://www.npmjs.com/package/semver supports it

**Comment by zam6ak** [comment]
semver supports it and it seems that `bump-regex` supports it as well, its just **not documented**....
IAW, I can do this with `gulp-bump` and it works fine:


```
gulp.task('bump-preminor', function(){
    gulp.src(['./package.json'])
        .pipe(bump({type:'preminor', preid: 'alpha'}))
        .pipe(gulp.dest('./'));
});
```
